# Generated by Django 3.1.7 on 2022-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220311_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/cakeImagePlacehlr.jpg', null=True, upload_to=''),
        ),
    ]
